In [1]:
import sys
sys.path.append('../') 
from visualisation import *
import xarray as xr
import dask, re
import geopandas as gpd
from shapely.geometry import Point
from geopy.geocoders import Nominatim
from tqdm import tqdm  # For progress bar in large datasets
from geopy.exc import GeocoderTimedOut

In [2]:
bom_path = "/home/hossein/CICCADA/BOM_NCI/2023/01/01/"
files = glob(bom_path+"*.nc")
len(files)

103

In [4]:
df = [xr.open_dataset(file).to_dataframe() for file in files[:15]]
df = pd.concat(df, axis=0).reset_index(drop=False)
df = df.dropna(subset='direct_normal_irradiance').reset_index(drop=True)
df['julian_date'] = pd.to_datetime(df['julian_date'], origin='julian', unit='D')
df = df.query(f"latitude >= -35 & latitude <= -34.6 & longitude >= 138.5 & longitude <= 138.8").reset_index(drop=True)
df['geometry'] = [Point(x,y) for x,y in zip(df['longitude'], df['latitude'])]
geo_list = df['geometry'].unique()
print('len(geo_list): ', len(geo_list))

len(geo_list):  2259710

In [5]:
i = 0

In [6]:
address_i = []
i_i = []
for _ in range(len(geo_list)):
    try:
        address = gpd.tools.reverse_geocode(geo_list[i], timeout=60)
        if address['address'].to_list()[0]!=None:
            print(address['address'], i)
            address_i.append(address)
            i_i.append(i)
    except Exception as e:
        pass
        print(e, i)
    i += 1

0    271, Brighton Road, 5044, Brighton Road, City ...
Name: address, dtype: object 1
0    Kent Avenue, 5046, City of Marion, South Austr...
Name: address, dtype: object 2
0    Sampson Road, 5043, City of Marion, South Aust...
Name: address, dtype: object 3
0    Styles Avenue, 5042, City of Mitcham, South Au...
Name: address, dtype: object 4
0    Crescent Avenue, 5041, City of Mitcham, South ...
Name: address, dtype: object 5
0    Gloucester Avenue, 5052, City of Mitcham, Sout...
Name: address, dtype: object 6
0    Brady Gully Track, 5052, City of Mitcham, Sout...
Name: address, dtype: object 7
0    Wilyawa Track, 5052, City of Mitcham, South Au...
Name: address, dtype: object 8
0    Charlick Road, 5156, City of Mitcham, South Au...
Name: address, dtype: object 9
0    5, Atkinson Road, 5152, Atkinson Road, Adelaid...
Name: address, dtype: object 10
0    Unnamed (No.HA1420) Heritage Agreement, 5152, ...
Name: address, dtype: object 11
0    St Margaret Drive, 5152, Stirling, South Austr...
Name: address, dtype: object 12
0    Radbone Road, 5155, Mount George, South Austra...
Name: address, dtype: object 13
0    Waters Road, 5155, Mount George, South Austral...
Name: address, dtype: object 14
0    Adelaide - Melbourne Standard Gauge Line, Griv...
Name: address, dtype: object 15
0    Glenelg Reef, South Australia, Australia
Name: address, dtype: object 16
0    Brighton Road, 5045, City of Holdfast Bay, Sou...
Name: address, dtype: object 17
0    Stop 20 Bray Street - South side, Bray Street,...
Name: address, dtype: object 18
0    Stop 15C Raglan Avenue - North side, Raglan Av...
Name: address, dtype: object 19
0    Clayton Crescent, 5039, City of Mitcham, South...
Name: address, dtype: object 20
0    Lincoln Avenue, 5041, City of Mitcham, South A...
Name: address, dtype: object 21
0    Scotch Junior School, Old Belair Road, 5062, O...
Name: address, dtype: object 22
0    Springfield Track, 5064, City of Mitcham, Sout...
Name: address, dtype: object 23
0    Mitcham Water Works, Yurrebilla Trail, 5150, Y...
Name: address, dtype: object 24
0    Pylon Trail, 5152, Adelaide Hills Council, Sou...
Name: address, dtype: object 25
0    Carro Track, 5152, Adelaide Hills Council, Sou...
Name: address, dtype: object 26
0    Ross Road, 5151, Adelaide Hills Council, South...
Name: address, dtype: object 27
0    Unnamed (No.HA357) Heritage Agreement, 5151, A...
Name: address, dtype: object 28
0    Muller Road, 5155, Mount George, South Austral...
Name: address, dtype: object 29
0    GahniaTrack, 5155, Mount George, South Austral...
Name: address, dtype: object 30
0    Spoehr Creek, Greenhill Road, 5144, Greenhill ...
Name: address, dtype: object 31
0    Barcoo outlet, 5045, City of West Torrens, Sou...
Name: address, dtype: object 32
0    Navaid Road, 5950, City of West Torrens, South...
Name: address, dtype: object 33
0    Stop 14 Mooringe Avenue - South side, Mooringe...
Name: address, dtype: object 34
0    Stop 9 Anzac Highway - North West side, Anzac ...
Name: address, dtype: object 35
0    From Gardens to Gulf, 72-74, East Avenue, 5035...
Name: address, dtype: object 36
0    210, King William Road, 5061, King William Roa...
Name: address, dtype: object 37
0    Concordia College and St Johns Lutheran School...
Name: address, dtype: object 38
0    Barr Smith Avenue, 5064, City of Unley, South ...
Name: address, dtype: object 39
0    Mount Osmond Fire Access Track, 5064, City of ...
Name: address, dtype: object 40
0    Pengana Spur Track, 5152, Adelaide Hills Counc...
Name: address, dtype: object 41
0    Bahn Spur Track, 5152, Adelaide Hills Council,...
Name: address, dtype: object 42
0    Samwell Road, 5141, Adelaide Hills Council, So...
Name: address, dtype: object 43
0    Swamp Road, 5142, Uraidla, South Australia, Au...
Name: address, dtype: object 44
0    Nicols Road, 5144, Carey Gully, South Australi...
Name: address, dtype: object 45
0    Unnamed (No.HA1368) Heritage Agreement, 5144, ...
Name: address, dtype: object 46
0    Lomandra Track, 5242, Balhannah, South Austral...
Name: address, dtype: object 47
0    Seaview Road, 5024, City of Charles Sturt, Sou...
Name: address, dtype: object 48
0    Stop 14 Tapleys Hill Road - East side, Tapleys...
Name: address, dtype: object 49
0    SoHo, Atura Circuit, 5950, Atura Circuit, City...
Name: address, dtype: object 50
0    Redin Street, 5033, City of West Torrens, Sout...
Name: address, dtype: object 51
0    Adelaide - Melbourne Standard Gauge Line, Rail...
Name: address, dtype: object 52
0    Stop L1 Peacock Road - East side, Peacock Road...
Name: address, dtype: object 53
0    Stop 5A Greenhill Road - North side, Greenhill...
Name: address, dtype: object 54
0    3, Sydney Street, 5065, Sydney Street, City of...
Name: address, dtype: object 55
0    541, Glynburn Road, 5066, Glynburn Road, City ...
Name: address, dtype: object 56
0    Second Creek, 5140, Adelaide Hills Council, So...
Name: address, dtype: object 57
0    Coach Road, 5141, Adelaide Hills Council, Sout...
Name: address, dtype: object 58
0    Magic Gully Track, 5141, Adelaide Hills Counci...
Name: address, dtype: object 59
0    Monomeith Road, 5137, Ashton, South Australia,...
Name: address, dtype: object 60
0    Lobethal Road, 5138, Basket Range, South Austr...
Name: address, dtype: object 61
0    Lobethal Road, 5138, Basket Range, South Austr...
Name: address, dtype: object 62
0    Unnamed (No.HA110) Heritage Agreement, 5139, F...
Name: address, dtype: object 63
0    Henley Memorial Oval, 5022, City of Charles St...
Name: address, dtype: object 64
0    Motley Avenue, 5024, City of Charles Sturt, So...
Name: address, dtype: object 65
0    Stop 11 White Avenue - East side, White Avenue...
Name: address, dtype: object 66
0    Torrensville, 5031, City of West Torrens, Sout...
Name: address, dtype: object 67
0    Port Road, 5000, Adelaide, South Australia, Au...
Name: address, dtype: object 68
0    Government House, King William Road, 5000, Kin...
Name: address, dtype: object 69
0    70, Rundle Street, 5067, Rundle Street, Kent T...
Name: address, dtype: object 70
0    Henry Street, 5067, The City of Norwood Payneh...
Name: address, dtype: object 71
0    The Parade, 5068, City of Burnside, South Aust...
Name: address, dtype: object 72
0    Magill Estate Kitchen, 78, Penfold Road, 5072,...
Name: address, dtype: object 73
0    Old Norton Summit Road, 5072, City of Burnside...
Name: address, dtype: object 74
0    Old Norton Summit Road, 5136, Norton Summit, S...
Name: address, dtype: object 75
0    Unnamed (No.HA62) Heritage Agreement, 5136, No...
Name: address, dtype: object 76
0    Marble Hill ruins, 17 Track, 5137, 17 Track, A...
Name: address, dtype: object 77
0    Pound Creek, 5138, Basket Range, South Austral...
Name: address, dtype: object 78
0    Hewletts Road, 5139, Forest Range, South Austr...
Name: address, dtype: object 79
0    Rainbow Street, 5022, City of Charles Sturt, S...
Name: address, dtype: object 80
0    Munro Avenue, 5023, City of Charles Sturt, Sou...
Name: address, dtype: object 81
0    Stop 20 Crittenden Road - North East side, Cri...
Name: address, dtype: object 82
0    Fischer Street, 5007, City of Charles Sturt, S...
Name: address, dtype: object 83
0    Drayton Street, 5007, City of Charles Sturt, S...
Name: address, dtype: object 84
0    Ngampa Yerta, Robe Terrace, 5081, Robe Terrace...
Name: address, dtype: object 85
0    Tenth Avenue, 5069, The City of Norwood Payneh...
Name: address, dtype: object 86
0    Portrush Road, 5070, The City of Norwood Payne...
Name: address, dtype: object 87
0    Rodney Avenue, 5073, Adelaide, South Australia...
Name: address, dtype: object 88
0    Egerton Avenue, 5073, Adelaide, South Australi...
Name: address, dtype: object 89
0    Morialta Falls Road, 5072, Adelaide Hills Coun...
Name: address, dtype: object 90
0    Moores Track, 5134, Montacute, South Australia...
Name: address, dtype: object 91
0    29 Track, 5134, Montacute, South Australia, Au...
Name: address, dtype: object 92
0    Hill Road, 5134, Montacute, South Australia, A...
Name: address, dtype: object 93
0    Sixth Creek, 5134, Montacute, South Australia,...
Name: address, dtype: object 94
0    1C Track, 5134, Montacute, South Australia, Au...
Name: address, dtype: object 95
0    Banksia Street, 5021, City of Charles Sturt, S...
Name: address, dtype: object 96
0    Dayman Avenue, 5014, City of Charles Sturt, So...
Name: address, dtype: object 97
0    Hughes Street South, 5011, City of Charles Stu...
Name: address, dtype: object 98
0    Stevens Street, 5008, City of Port Adelaide En...
Name: address, dtype: object 99
0    Islington Court, 5008, City of Port Adelaide E...
Name: address, dtype: object 100
0    Newark Street, 5082, City of Prospect, South A...
Name: address, dtype: object 101
0    Stop 16 Hampstead Road - East side, Hampstead ...
Name: address, dtype: object 102
0    Clarence Court, 5087, City of Port Adelaide En...
Name: address, dtype: object 103
0    Leslie Avenue, 5074, Adelaide, South Australia...
Name: address, dtype: object 104
0    Capezzone Court, 5074, Adelaide, South Austral...
Name: address, dtype: object 105
0    Judith Drive, 5076, Adelaide, South Australia,...
Name: address, dtype: object 106
0    Summit Track, 5134, Montacute, South Australia...
Name: address, dtype: object 107
0    Pinkerton Gully Road, 5134, Montacute, South A...
Name: address, dtype: object 108
0    Valley Road, 5134, Montacute, South Australia,...
Name: address, dtype: object 109
0    Stone Hut Road, 5134, Montacute, South Austral...
Name: address, dtype: object 110
0    Kangaroo Creek, 5232, Cudlee Creek, South Aust...
Name: address, dtype: object 111
0    Settlers Drive, 5021, City of Charles Sturt, S...
Name: address, dtype: object 112
0    61, Buller Terrace, 5014, Buller Terrace, City...
Name: address, dtype: object 113
0    Stop 29C Park Avenue - North side, Park Avenue...
Name: address, dtype: object 114
0    Hilton Court, 5010, City of Port Adelaide Enfi...
Name: address, dtype: object 115
0    Carroll Avenue, 5084, City of Port Adelaide En...
Name: address, dtype: object 116
0    Barton Street, 5084, City of Port Adelaide Enf...
Name: address, dtype: object 117
0    Grundy Road, 5085, City of Port Adelaide Enfie...
Name: address, dtype: object 118
0    Hawkins Avenue, 5086, City of Port Adelaide En...
Name: address, dtype: object 119
0    Sudholz Road, 5087, City of Port Adelaide Enfi...
Name: address, dtype: object 120
0    Balmoral Road, 5075, City of Tea Tree Gully, S...
Name: address, dtype: object 121
0    Palm Court, 5076, Adelaide, South Australia, A...
Name: address, dtype: object 122
0    Gorge Road, 5076, Campbelltown City Council, S...
Name: address, dtype: object 123
0    Gorge Road, 5134, Montacute, South Australia, ...
Name: address, dtype: object 124
0    Gorge Road, 5132, Adelaide Hills Council, Sout...
Name: address, dtype: object 125
0    Gorge Road, 5232, Cudlee Creek, South Australi...
Name: address, dtype: object 126
0    Prairie Road, 5232, Cudlee Creek, South Austra...
Name: address, dtype: object 127
0    Semaphore Road, 5015, City of Port Adelaide En...
Name: address, dtype: object 128
0    Francis Street, 5015, City of Port Adelaide En...
Name: address, dtype: object 129
0    North Arm Road, 5013, City of Port Adelaide En...
Name: address, dtype: object 130
0    Adelaide Marble Specialists, 122, South Terrac...
Name: address, dtype: object 131
0    Cormack Road, 5013, City of Port Adelaide Enfi...
Name: address, dtype: object 132
0    Stop 28 Port Wakefield Road - East side, Port ...
Name: address, dtype: object 133
0    ServiceFM Stadium, Matildas Drive, 5094, Matil...
Name: address, dtype: object 134
0    Outback Court, 5098, City of Salisbury, South ...
Name: address, dtype: object 135
0    Sherwood Avenue, 5093, City of Salisbury, Sout...
Name: address, dtype: object 136
0    32-42, Heysen Avenue, 5090, Heysen Avenue, Cit...
Name: address, dtype: object 137
0    Hope Valley Bowls Club, Deakin Avenue, 5090, D...
Name: address, dtype: object 138
0    Lower North East Road, 5091, City of Tea Tree ...
Name: address, dtype: object 139
0    Water Treatment Facility, 5091, City of Tea Tr...
Name: address, dtype: object 140
0    Murphy Road, 5132, Adelaide Hills Council, Sou...
Name: address, dtype: object 141
0    Paracombe CFS, Paracombe Road, 5133, Paracombe...
Name: address, dtype: object 142
0    8, 5231, Adelaide Hills Council, South Austral...
Name: address, dtype: object 143
0    Dover Terrace, 5016, City of Port Adelaide Enf...
Name: address, dtype: object 144
0    Grand Trunkway, 5013, City of Port Adelaide En...
Name: address, dtype: object 145
0    Club Road, 5960, City of Port Adelaide Enfield...
Name: address, dtype: object 146
0    Northern Connector, 5094, City of Salisbury, S...
Name: address, dtype: object 147
0    Salisbury Highway, 5094, City of Salisbury, So...
Name: address, dtype: object 148
0    Gawler Line, Dixon Lane, 5095, Dixon Lane, Cit...
Name: address, dtype: object 149
0    Third Avenue, 5095, City of Salisbury, South A...
Name: address, dtype: object 150
0    Bridge Road, 5098, City of Salisbury, South Au...
Name: address, dtype: object 151
0    Clarke Street, 5098, City of Salisbury, South ...
Name: address, dtype: object 152
0    Carruthers Drive, 5092, City of Tea Tree Gully...
Name: address, dtype: object 153
0    Ashley Avenue, 5097, City of Tea Tree Gully, S...
Name: address, dtype: object 154
0    Pioneer Medical Centre, 1291, North East Road,...
Name: address, dtype: object 155
0    Newmans Nursery, 1361, North East Road, 5097, ...
Name: address, dtype: object 156
0    Milbanca Road, 5131, Lower Hermitage, South Au...
Name: address, dtype: object 157
0    Chapman Road, 5133, Inglewood, South Australia...
Name: address, dtype: object 158
0    North East Road, 5133, Inglewood, South Austra...
Name: address, dtype: object 159
0    Wallace Street, 5017, City of Port Adelaide En...
Name: address, dtype: object 160
0    Grand Trunkway, 5960, South Australia, Australia
Name: address, dtype: object 161
0    Dolphin Sanctuary Kayak Tours, Garden Island R...
Name: address, dtype: object 162
0    Broad Creek, 5094, City of Salisbury, South Au...
Name: address, dtype: object 163
0    Tapa Martinthi Yala, 5094, City of Salisbury, ...
Name: address, dtype: object 164
0    Maquarie Street, 5095, City of Salisbury, Sout...
Name: address, dtype: object 165
0    Lucia Place, 5095, City of Salisbury, South Au...
Name: address, dtype: object 166
0    Main North Road, 5096, City of Salisbury, Sout...
Name: address, dtype: object 167
0    Granada Avenue, 5096, City of Salisbury, South...
Name: address, dtype: object 168
0    Borrowdale Court, 5127, City of Tea Tree Gully...
Name: address, dtype: object 169
0    Pump Station Chute, 5127, City of Tea Tree Gul...
Name: address, dtype: object 170
0    Littler Drive, 5126, City of Tea Tree Gully, S...
Name: address, dtype: object 171
0    Mannara Road, 5126, City of Tea Tree Gully, So...
Name: address, dtype: object 172
0    Hermitage CFS, 300, Range Road North, 5131, Ra...
Name: address, dtype: object 173
0    Lower Hermitage, 5131, South Australia, Australia
Name: address, dtype: object 174
0    Millbrook Road, 5133, Inglewood, South Austral...
Name: address, dtype: object 175
0    Biodiversity Park, 5018, City of Port Adelaide...
Name: address, dtype: object 176
0    Quarantine Power Station, 5960, South Australi...
Name: address, dtype: object 177
0    Barker Inlet, 5960, South Australia, Australia
Name: address, dtype: object 178
0    Barker Inlet-St Kilda Aquatic Reserve, South A...
Name: address, dtype: object 179
0    Northern Connector, 5110, City of Salisbury, S...
Name: address, dtype: object 180
0    Brooke Street, 5107, City of Salisbury, South ...
Name: address, dtype: object 181
0    Blyth Avenue, 5107, City of Salisbury, South A...
Name: address, dtype: object 182
0    Acrylon Road, 5106, City of Salisbury, South A...
Name: address, dtype: object 183
0    10, Sarah Street, 5109, Sarah Street, City of ...
Name: address, dtype: object 184
0    Kafnarfa Trail, 5109, City of Salisbury, South...
Name: address, dtype: object 185
0    Simpson Court, 5125, City of Tea Tree Gully, S...
Name: address, dtype: object 186
0    Wallsall Lane, 5125, City of Tea Tree Gully, S...
Name: address, dtype: object 187
0    Crouch Road, 5125, City of Tea Tree Gully, Sou...
Name: address, dtype: object 188
0    Little Para River, 5125, City of Tea Tree Gull...
Name: address, dtype: object 189
0    Lower Hermitage Track, 5131, Upper Hermitage, ...
Name: address, dtype: object 190
0    Richardson Road, 5133, Inglewood, South Austra...
Name: address, dtype: object 191
0    Pelican Point1, 5018, South Australia, Australia
Name: address, dtype: object 192
0    Snapper Point, 5017, South Australia, Australia
Name: address, dtype: object 193
0    Barker Inlet, 5110, City of Salisbury, South A...
Name: address, dtype: object 194
0    Northern Connector, 5110, City of Salisbury, S...
Name: address, dtype: object 196
0    Crosby Way, 5108, City of Salisbury, South Aus...
Name: address, dtype: object 197
0    Metala Road, 5108, City of Salisbury, South Au...
Name: address, dtype: object 198
0    Shannon Street, 5108, City of Salisbury, South...
Name: address, dtype: object 199
0    Chatswood Way, 5109, City of Salisbury, South ...
Name: address, dtype: object 200
0    St Albans Drive, 5109, City of Salisbury, Sout...
Name: address, dtype: object 201
0    Chandler Grove, 5125, City of Tea Tree Gully, ...
Name: address, dtype: object 202
0    5 Lakeridge Court, 5, Lakeridge Court, 5125, L...
Name: address, dtype: object 203
0    Para Valley Road, 5125, City of Tea Tree Gully...
Name: address, dtype: object 204
0    Little Para River, 5125, City of Tea Tree Gull...
Name: address, dtype: object 205
0    Hannaford Hump Road, 5133, City of Playford, S...
Name: address, dtype: object 206
0    MG13 Track, 5133, City of Playford, South Aust...
Name: address, dtype: object 207
0    St Kilda heritage tramway, St Kilda Road, 5110...
Name: address, dtype: object 210
0    Northern Connector, 5110, City of Salisbury, S...
Name: address, dtype: object 212
0    Wachtel Crescent, 5110, City of Salisbury, Sou...
Name: address, dtype: object 213
0    Lake Windemere School, 17, Uraidla Avenue, 510...
Name: address, dtype: object 214
0    Woomera Avenue, 5111, City of Salisbury, South...
Name: address, dtype: object 215
0    Stop 57 Hogarth Road - South side, Hogarth Roa...
Name: address, dtype: object 216
0    Bogan Road, 5112, City of Playford, South Aust...
Name: address, dtype: object 217
0    Little Para Reservoir, 5125, City of Tea Tree ...
Name: address, dtype: object 219
0    Gould Creek, 5125, City of Tea Tree Gully, Sou...
Name: address, dtype: object 220
0    Goulds Creek Road, 5114, City of Playford, Sou...
Name: address, dtype: object 221
0    One Tree Hill Road, City of Tea Tree Gully, So...
Name: address, dtype: object 222
0    MG1 Track, City of Playford, South Australia, ...
Name: address, dtype: object 223
0    Brooks Road, 5120, City of Playford, South Aus...
Name: address, dtype: object 226
0    Berno Road, 5110, City of Playford, South Aust...
Name: address, dtype: object 227
0    Stop 65 Port Wakefield Road - North East side,...
Name: address, dtype: object 228
0    Edinburgh Road, 5110, City of Salisbury, South...
Name: address, dtype: object 229
0    Edinburgh Road, 5111, City of Salisbury, South...
Name: address, dtype: object 230
0    West Avenue, 5111, City of Salisbury, South Au...
Name: address, dtype: object 231
0    Gawler Line, elizabeth backway footpath, 5112,...
Name: address, dtype: object 232
0    Hull Street, 5112, City of Playford, South Aus...
Name: address, dtype: object 233
0    Greenway Crescent, 5112, City of Playford, Sou...
Name: address, dtype: object 234
0    Yelki Road, 5114, City of Playford, South Aust...
Name: address, dtype: object 235
0    Goulds Road, 5114, City of Playford, South Aus...

In [14]:
postcode = re.search(r'\b\d{4}\b', address_i[0]['address'].to_list()[0])
postcode.group()

'5044'

In [53]:
i_i[0], address_i[0]['address'].to_list()[0]

(1,
 '271, Brighton Road, 5044, Brighton Road, City of Holdfast Bay, South Australia, Australia')

In [67]:
len(address_i), len(i_i)

(324, 324)

In [68]:
postcode_i = [re.search(r'\b\d{4}\b', i['address'].to_list()[0]) for i in address_i]
postcode_i = [i.group() if i is not None else 'None' for i in postcode_i]
lat_i = [geo_list[i].y for i in i_i]
lon_i = [geo_list[i].x for i in i_i]

In [70]:
df_address = pd.DataFrame({'postcode': postcode_i, 'latitude': lat_i, 'longitude': lon_i})

In [76]:
df.merge(df_address, on=['latitude', 'longitude'], how='inner')

,time,latitude,longitude,crs,surface_global_irradiance,direct_normal_irradiance,surface_diffuse_irradiance,quality_mask,cloud_type,cloud_optical_depth,solar_elevation,solar_azimuth,julian_date,geometry,postcode
0,2022-12-31 19:30:00,-35.000000,138.520004,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.52000427246094 -35),5044.0
1,2022-12-31 19:30:00,-35.000000,138.539993,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.5399932861328 -35),5046.0
2,2022-12-31 19:30:00,-35.000000,138.559998,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.55999755859375 -35),5043.0
3,2022-12-31 19:30:00,-35.000000,138.580002,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.5800018310547 -35),5042.0
4,2022-12-31 19:30:00,-35.000000,138.600006,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.2,118.8,2022-12-31 19:37:58.876139225,POINT (138.60000610351562 -35),5041.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2911,2022-12-31 21:20:00,-34.599998,138.720001,-2147483647,329.79,773.72,56.93,1.0,0.0,0.0,20.7,104.4,2022-12-31 21:27:57.246786650,POINT (138.72000122070312 -34.599998474121094),5118.0
2912,2022-12-31 21:20:00,-34.599998,138.740005,-2147483647,330.33,774.65,56.91,1.0,0.0,0.0,20.7,104.4,2022-12-31 21:27:57.246786650,POINT (138.74000549316406 -34.599998474121094),5118.0
2913,2022-12-31 21:20:00,-34.599998,138.759995,-2147483647,330.79,779.60,55.40,1.0,0.0,0.0,20.7,104.4,2022-12-31 21:27:57.246786650,POINT (138.75999450683594 -34.599998474121094),5118.0
2914,2022-12-31 21:20:00,-34.599998,138.779999,-2147483647,332.38,784.38,55.07,1.0,0.0,0.0,20.7,104.3,2022-12-31 21:27:57.246786650,POINT (138.77999877929688 -34.599998474121094),5118.0
2915,2022-12-31 21:20:00,-34.599998,138.800003,-2147483647,333.90,788.95,54.74,1.0,0.0,0.0,20.7,104.3,2022-12-31 21:27:57.246786650,POINT (138.8000030517578 -34.599998474121094),5350.0

In [72]:
df_address.to_csv('Adelide_postcode_points.csv', index=False)

In [73]:
df_address = pd.read_csv('Adelide_postcode_points.csv')

In [74]:
df_address

     postcode   latitude   longitude
0      5044.0 -35.000000  138.520004
1      5046.0 -35.000000  138.539993
2      5043.0 -35.000000  138.559998
3      5042.0 -35.000000  138.580002
4      5041.0 -35.000000  138.600006
..        ...        ...         ...
319    5118.0 -34.599998  138.720001
320    5118.0 -34.599998  138.740005
321    5118.0 -34.599998  138.759995
322    5118.0 -34.599998  138.779999
323    5350.0 -34.599998  138.800003

[324 rows x 3 columns]

In [61]:
df[df['latitude']==geo_list[1].y]

,time,latitude,longitude,crs,surface_global_irradiance,direct_normal_irradiance,surface_diffuse_irradiance,quality_mask,cloud_type,cloud_optical_depth,solar_elevation,solar_azimuth,julian_date,geometry
0,2022-12-31 19:30:00,-35.0,138.500000,-2147483647,0.00,0.00,0.00,4.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.5 -35)
1,2022-12-31 19:30:00,-35.0,138.520004,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.52000427246094 -35)
2,2022-12-31 19:30:00,-35.0,138.539993,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.5399932861328 -35)
3,2022-12-31 19:30:00,-35.0,138.559998,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.55999755859375 -35)
4,2022-12-31 19:30:00,-35.0,138.580002,-2147483647,0.00,0.00,0.00,1.0,0.0,0.0,-0.3,118.8,2022-12-31 19:37:58.876139225,POINT (138.5800018310547 -35)
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2699,2022-12-31 21:20:00,-35.0,138.720001,-2147483647,348.10,836.80,51.46,1.0,0.0,0.0,20.8,104.2,2022-12-31 21:27:58.876148160,POINT (138.72000122070312 -35)
2700,2022-12-31 21:20:00,-35.0,138.740005,-2147483647,346.43,829.07,52.29,1.0,0.0,0.0,20.8,104.2,2022-12-31 21:27:58.876148160,POINT (138.74000549316406 -35)
2701,2022-12-31 21:20:00,-35.0,138.759995,-2147483647,345.46,825.71,52.27,1.0,0.0,0.0,20.8,104.2,2022-12-31 21:27:58.876148160,POINT (138.75999450683594 -35)
2702,2022-12-31 21:20:00,-35.0,138.779999,-2147483647,343.31,816.27,53.23,1.0,0.0,0.0,20.8,104.2,2022-12-31 21:27:58.876148160,POINT (138.77999877929688 -35)
2703,2022-12-31 21:20:00,-35.0,138.800003,-2147483647,343.31,816.27,53.23,1.0,0.0,0.0,20.8,104.2,2022-12-31 21:27:58.876148160,POINT (138.8000030517578 -35)

In [ ]:

# Add a reverse geocoding function
def get_postcode(point):
    location = geolocator.reverse((point.y, point.x), exactly_one=True)
    if location and 'postcode' in location.raw['address']:
        return location.raw['address']['postcode']
    return None

# Apply with progress bar
tqdm.pandas()
gdf['Postcode'] = gdf['geometry'].progress_apply(get_postcode)

print(gdf)

In [1]:
np.sort(df0.loc[0, 'julian_date'])

NameError: name 'np' is not defined

In [27]:
np.sort(df0.loc[10, 'julian_date'])

array(['2020-11-19T18:38:35.534292158', '2020-11-19T18:48:35.534296630',
       '2020-11-19T18:58:35.534301101', '2020-11-19T19:08:35.534305573',
       '2020-11-19T19:18:35.534310045', '2020-11-19T19:28:35.534274280',
       '2020-11-19T19:38:35.534278752', '2020-11-19T19:48:35.534283223',
       '2020-11-19T19:58:35.534287695'], dtype='datetime64[ns]')

In [28]:
np.sort(df0.loc[22, 'time'])

array(['2020-11-19T18:30:00.000000000', '2020-11-19T18:40:00.000000000',
       '2020-11-19T18:50:00.000000000', '2020-11-19T19:00:00.000000000',
       '2020-11-19T19:10:00.000000000', '2020-11-19T19:20:00.000000000',
       '2020-11-19T19:30:00.000000000', '2020-11-19T19:40:00.000000000',
       '2020-11-19T19:50:00.000000000'], dtype='datetime64[ns]')

In [ ]:

# print(df.columns)
# print(df['julian_date'][0])
df = df.query('direct_normal_irradiance > 0').drop_duplicates(subset='julian_date').loc[:, ['julian_date', 'direct_normal_irradiance', 'surface_global_irradiance',
 'surface_diffuse_irradiance', 'cloud_optical_depth', 'cloud_type']]
print(df['julian_date'].min(), df['julian_date'].max())
print(df[:30])