In [6]:
from Data_query.trino_config import *
import json
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
stop_trino()

In [7]:
big_workers = 0
workers = 1
num_workers = max(workers, big_workers)
ensure_trino_running(worker_desired_count = workers, big_worker_desired_count=big_workers)
sleep(30)

Trino service is not running. Starting the service...
Trino service triggered.
Service trino-service is now stable.

In [ ]:
iceberg_sql(""" select  distinct site_id, state, dnsp_name, 
            case when manufacturer='Goodwe' then 'GoodWe'
            when manufacturer='Solaredge' then 'SolarEdge'
            when manufacturer='SolaX Power' then  'SolaX' else manufacturer end as OEM
            from meta_up23c
            where manufacturer in ('SolarEdge', 'Fronius', 'SMA', 'GoodWe', 'Solax', 'Sungrow', 'Solis', 'Solaredge', 'Goodwe', 'SolaX', 'SolaX Power')
            and dnsp_name in ('Energex', 'Ergon', 'Ausgrid', 'SAPN')
            order by OEM
""").to_csv('OEM_sites_visible_OEM.csv', index=False)

In [8]:
iceberg_sql(""" select   state, dnsp_name, manufacturer, count(distinct site_id) from meta_up23c
            where manufacturer  in ('SolarEdge', 'Fronius', 'SMA', 'GoodWe', 'Solax', 'Sungrow', 'Solis', 'Solaredge', 'Goodwe', 'SolaX', 'SolaX Power')
            and dnsp_name in ('Energex', 'Ergon', 'Ausgrid', 'SAPN')
            group by state, dnsp_name, manufacturer
            order by manufacturer
""")

Empty DataFrame
Columns: [state, dnsp_name, manufacturer, _col3]
Index: []

In [5]:
iceberg_sql(""" select distinct manufacturer from meta_up23c
""")

            manufacturer
0                Sungrow
1                Fronius
2                    SMA
3       Generic Inverter
4                 GoodWe
5              SolarEdge
6                 Huawei
7           Delta Energy
8                  SolaX
9                  Solis
10               Growatt
11           Samil Power
12                   ABB
13               Xantrex
14                   JFY
15               GESolar
16            Zeversolar
17                Aurora
18                 Fimer
19                 SOFAR
20              Clenergy
21    Schneider Electric
22  Bosch Power Tec GmbH
23                  INVT
24                   EKO
25       KACO new energy
26               Eversol
27              Oelmaier
28              Ingeteam
29               Generic
30              SolarMax
31                   SAJ
32             Sunny Roo
33                 Omnik
34               Ginlong
35                 Sharp
36             Solplanet
37              Latronic
38        Canadian Solar