In [1]:
import polars as pl
from trino_connection import local_trino_engine, hive_sql, iceberg_sql

# before this make sure 
# EC2 instance is running trino connection to the schemas

In [2]:
# hive individual query
hive_sql("SHOW SCHEMAS")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-8e8uo72npn6f2dnyrceshhjreq
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-8e8uo72npn6f2dnyrceshhjreq.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-8e8uo72npn6f2dnyrceshhjreq]

                    Schema
0                  bom_nci
1                  default
2                elb_logdb
3       information_schema
4                 sapn2022
5          solar_analytics
6  solar_analytics_iceberg
7                  test_db
8               type_probe

In [3]:
# iceberg indiviudal query
iceberg_sql("show schemas")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-vk2vh32d78h629jjsf9ysq26fe
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-vk2vh32d78h629jjsf9ysq26fe.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-vk2vh32d78h629jjsf9ysq26fe]

                    Schema
0                  bom_nci
1                  default
2                elb_logdb
3       information_schema
4                 sapn2022
5          solar_analytics
6  solar_analytics_iceberg
7                   system
8                  test_db
9               type_probe

In [4]:
# hive individual query
hive_sql("SHOW tables", schema = "solar_analytics")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-2gn5pridarlhh84hcapabnv9ti
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-2gn5pridarlhh84hcapabnv9ti.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-2gn5pridarlhh84hcapabnv9ti]

                                          Table
0                                      circuits
1                            compliance_voltvar
2                           compliance_voltwatt
3                         meta_single_inverters
4          meta_single_inverters_wrong_capacity
5   meta_single_inverters_wrong_capacity_up2_3c
6                              partition_lookup
7                                raw_bom_2024_6
8                                         sites
9                             test_sola_2025_12
10                             test_sola_2025_7
11                             test_sola_2025_8
12                             test_sola_2025_9

In [5]:
# iceberg indiviudal query
iceberg_sql("show tables", schema = "solar_analytics_iceberg")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-eg7shlnxiyti5vblqsgcedqq5a
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-eg7shlnxiyti5vblqsgcedqq5a.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-eg7shlnxiyti5vblqsgcedqq5a]

                                       Table
0                          all_uncurtailedpv
1                       all_uncurtailedpv_v2
2         all_uncurtailedpv_v2_flex_included
3                                   circuits
4                     conformance_antiisland
5                        conformance_sust_op
6                     conformance_sust_op_3w
7                        conformance_voltvar
8                     conformance_voltvar_v2
9       conformance_voltvar_v2_flex_included
10                      conformance_voltwatt
11                   conformance_voltwatt_v2
12     conformance_voltwatt_v2_flex_included
13                   conformance_voltwattghi
14                conformance_voltwattghi_v2
15  conformance_voltwattghi_v2_flex_included
16                                meta_up23c
17                         pv_ghi_norm_model
18                      pv_ghi_norm_model_v2
19        pv_ghi_norm_model_v2_flex_included
20                review_conformance_sust_op
21                  single_site_pv_ghi_model
22                                     sites
23                                split_days
24                             split_days_v2
25               split_days_v2_flex_included
26                           structured_data
27                        structured_data_v2
28          structured_data_v2_flex_included
29                                        ts
30                    voltwatt_uncurtailedpv

In [6]:
# use this for continued querying of the data
catalog = "iceberg"
with local_trino_engine(catalog = catalog) as engine:
    schemas = pl.read_database(query="SHOW SCHEMAS", connection=engine)

print(schemas)

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-tdjbuhasbx2r8kjis572t2y4xy
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-tdjbuhasbx2r8kjis572t2y4xy.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-tdjbuhasbx2r8kjis572t2y4xy]
                    Schema
0                  bom_nci
1                  default
2                elb_logdb
3       information_schema
4                 sapn2022
5          solar_analytics
6  solar_analytics_iceberg
7                   system
8                  test_db
9               type_probe

In [7]:
# iceberg_sql("SELECT * FROM ts where circuit_id = 239893 and year=2024 and month=10 limit 10")

In [8]:
# passing schema name explicitly, same as defualt here
iceberg_sql("SELECT * FROM sites limit 10", schema = "solar_analytics_iceberg")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-h2geoqpcj2fexpru2fqp4gtkii
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-h2geoqpcj2fexpru2fqp4gtkii.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-h2geoqpcj2fexpru2fqp4gtkii]

      site_id  ac_capacity_kw  postcode
0  1944472430             5.0      2502
1  1555410224            10.0      4814
2   758643151             3.6      4812
3  1669657679             6.0      2525
4  1947677239            20.0      2680
5   565382247            10.0      4715
6   543357583            10.0      4740
7   826425816             5.0      4551
8  1682670886             5.0      2264
9  1334476516            29.9      4341

In [9]:
# passing schema name explicitly, same as defualt here
hive_sql("SELECT * FROM circuits limit 10", schema = "solar_analytics")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-hhrvf6fch25g46v3an92q9znby
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-hhrvf6fch25g46v3an92q9znby.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-hhrvf6fch25g46v3an92q9znby]

,site_id,device_id,circuit_id,device_type,circuit_polarity,circuit_type,is_pv
0,484720983,135961,84703,Watt Watcher,1,pv_site_net,True
1,484720983,135961,84704,Watt Watcher,1,pv_site_net,True
2,484720983,135961,84705,Watt Watcher,1,pv_site_net,True
3,150652475,140483,658777,Watt Watcher,1,ac_load_net,False
4,150652475,140483,658778,Watt Watcher,1,ac_load_net,False
5,150652475,140483,658782,Watt Watcher,1,pv_site_net,True
6,150652475,140483,658779,Watt Watcher,1,ac_load_net,False
7,1988982127,134898,630461,CATCH Power,1,ac_load_net,False
8,1988982127,134898,630462,CATCH Power,-1,pv_site_net,True
9,2137155135,135871,594217,Watt Watcher,1,ac_load_net,False

In [12]:
# passing schema name explicitly, same as defualt here
hive_sql("SELECT * FROM sites limit 10", schema = "solar_analytics")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-pk8zul4rall5h95pduln4ob3qi
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-pk8zul4rall5h95pduln4ob3qi.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-pk8zul4rall5h95pduln4ob3qi]

,site_id,state,postcode,longitude,latitude,dnsp_name,dc_capacity_kw,ac_capacity_kw,export_limit_kw,monitoring_start,inverter_count,pv_install_date,manufacturer,model,ac_capacity_kw_exploaded,installed_after_18_dec_2021
0,1944472430,NSW,2502.0,150.85,-34.470,Endeavour,5.18,5.0,3.0,2021-08-09,1.0,2021-08-09,Sungrow,SG5KTL,5.0,False
1,1555410224,QLD,4814.0,146.75,-19.305,Ergon,13.28,10.0,5.0,2024-03-07,1.0,2024-03-06,Sungrow,SG10RS-ADA,10.0,True
2,623277618,QLD,4211.0,153.30,-27.990,Energex,15.75,10.0,5.0,2024-03-18,1.0,2023-06-30,Fronius,Primo GEN24 10.0,10.0,True
3,1245528685,QLD,4078.0,152.95,-27.630,Energex,15.00,10.0,6.8,2024-09-18,1.0,2024-09-18,Generic Inverter,10.0kW,10.0,True
4,1651877625,NSW,2350.0,151.70,-30.510,Essential,11.55,9.6,5.0,2019-06-27,2.0,2018-11-02,Generic Inverter,5kW,5.0,False
5,1651877625,NSW,2350.0,151.70,-30.510,Essential,11.55,9.6,5.0,2019-06-27,2.0,2018-11-02,Generic Inverter,4.6kW,4.6,False
6,574698270,VIC,3030.0,144.75,-37.890,Powercor,97.20,82.8,15.0,2021-07-27,1.0,2021-07-15,SolarEdge,SE82.8K,82.8,False
7,1492891952,QLD,4700.0,150.50,-23.400,Ergon,275.40,220.0,213.0,2023-02-15,2.0,2023-02-15,SMA,Core2 STP 110-60,110.0,True
8,2089597856,VIC,3133.0,145.20,-37.845,Ausnet,89.10,75.0,0.0,2018-12-10,3.0,2018-12-10,SMA,Sunny Tripower STP25000 TL-30,25.0,False
9,141527446,NT,822.0,131.05,-12.555,Power and Water Corporation,99.44,79.9,0.0,2024-04-29,2.0,2024-04-29,Sungrow,SG30CX,29.9,True

In [10]:
iceberg_sql("SELECT * FROM circuits limit 10")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-3uu4ccj3sy4jyt7pdojxxp83ay
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-3uu4ccj3sy4jyt7pdojxxp83ay.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-3uu4ccj3sy4jyt7pdojxxp83ay]

      site_id  circuit_id  circuit_polarity  is_pv
0   484720983       84703                 1   True
1   150652475      658777                 1  False
2   150652475      658778                 1  False
3   150652475      658782                 1   True
4   150652475      658779                 1  False
5   484720983       84704                 1   True
6   484720983       84705                 1   True
7  1988982127      630461                 1  False
8  1988982127      630462                -1   True
9  2137155135      594217                 1  False

In [11]:
# this seems like HS created this one
iceberg_sql("SELECT * FROM meta_up23c limit 10")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-yzgikyjg2kirtps4yeknnhc2ca
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-yzgikyjg2kirtps4yeknnhc2ca.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-yzgikyjg2kirtps4yeknnhc2ca]

,site_id,state,postcode,longitude,latitude,dnsp_name,dc_capacity_kw,ac_capacity_kw,export_limit_kw,monitoring_start,...,m_id,avg_pf,std_pf,pf_99,pf_01,n_long,n_lat,distance_km,s_99,flex_export_detected
0,1233585204,VIC,3140,145.35,-37.755,Ausnet,5.10,5.0,None,2019-08-09,...,M17,0.998620,0.000225,0.999304,0.998327,145.34,-37.76,1.241018,4.614773,False
1,158521185,NSW,2488,153.55,-28.350,Essential,10.54,8.0,None,2019-10-31,...,M39,0.999972,0.000029,0.999994,0.999873,153.56,-28.36,1.569777,7.975964,False
2,2083958230,NSW,2763,150.90,-33.750,Endeavour,5.28,5.0,None,2020-01-07,...,M13,0.999996,0.000008,1.000000,0.999959,150.90,-33.74,1.110000,4.930158,True
3,248529252,VIC,3140,145.35,-37.755,Ausnet,5.06,5.0,None,2020-03-04,...,M13,0.991457,0.006766,0.997926,0.970164,145.34,-37.76,1.241018,3.980736,False
4,248529252,VIC,3140,145.35,-37.755,Ausnet,5.06,5.0,None,2020-03-04,...,M13,0.991457,0.006766,0.997926,0.970164,145.34,-37.76,1.241018,3.980736,False
5,248529252,VIC,3140,145.35,-37.755,Ausnet,5.06,5.0,None,2020-03-04,...,M13,0.991457,0.006766,0.997926,0.970164,145.34,-37.76,1.241018,3.980736,False
6,804338564,QLD,4670,152.45,-24.795,Ergon,5.28,5.0,None,2020-06-10,...,M27,0.970547,0.015425,0.993794,0.923624,152.44,-24.80,1.241018,4.819746,False
7,804338564,QLD,4670,152.45,-24.795,Ergon,5.28,5.0,None,2020-06-10,...,M27,0.970547,0.015425,0.993794,0.923624,152.44,-24.80,1.241018,4.819746,False
8,1706869440,NSW,2212,151.00,-33.975,Ausgrid,99.60,82.8,None,2020-07-06,...,M13,0.999939,0.000022,0.999977,0.999878,151.00,-33.98,0.555000,74.199160,False
9,1706869440,NSW,2212,151.00,-33.975,Ausgrid,99.60,82.8,None,2020-07-06,...,M13,0.999939,0.000022,0.999977,0.999878,151.00,-33.98,0.555000,74.199160,False