In [1]:
import polars as pl
from trino_connection_local_to_s3 import local_trino_engine, hive_sql, iceberg_sql

# before this make sure 
# EC2 instance is running trino connection to the schemas

In [2]:
# hive individual query
hive_sql("SHOW SCHEMAS")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-9jfbp2ina6ryyfv6ypuhpaax5q
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-9jfbp2ina6ryyfv6ypuhpaax5q.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-9jfbp2ina6ryyfv6ypuhpaax5q]

shape: (9, 1)
┌─────────────────────────┐
│ Schema                  │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ bom_nci                 │
│ default                 │
│ elb_logdb               │
│ information_schema      │
│ sapn2022                │
│ solar_analytics         │
│ solar_analytics_iceberg │
│ test_db                 │
│ type_probe              │
└─────────────────────────┘

In [3]:
# iceberg indiviudal query
iceberg_sql("show schemas")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-krs6sb7i5evifhqkjjus2777le
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-krs6sb7i5evifhqkjjus2777le.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-krs6sb7i5evifhqkjjus2777le]

shape: (10, 1)
┌─────────────────────────┐
│ Schema                  │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ bom_nci                 │
│ default                 │
│ elb_logdb               │
│ information_schema      │
│ sapn2022                │
│ solar_analytics         │
│ solar_analytics_iceberg │
│ system                  │
│ test_db                 │
│ type_probe              │
└─────────────────────────┘

In [4]:
# hive individual query
hive_sql("SHOW tables", schema = "solar_analytics")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-3x49qrhc62ughnqksndg7ng5a4
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-3x49qrhc62ughnqksndg7ng5a4.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-3x49qrhc62ughnqksndg7ng5a4]

shape: (13, 1)
┌─────────────────────────────────┐
│ Table                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ circuits                        │
│ compliance_voltvar              │
│ compliance_voltwatt             │
│ meta_single_inverters           │
│ meta_single_inverters_wrong_ca… │
│ …                               │
│ sites                           │
│ test_sola_2025_12               │
│ test_sola_2025_7                │
│ test_sola_2025_8                │
│ test_sola_2025_9                │
└─────────────────────────────────┘

In [5]:
# iceberg indiviudal query
iceberg_sql("show tables", schema = "solar_analytics_iceberg")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-srx7ar5z2gjyslpzo56eh9dciy
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-srx7ar5z2gjyslpzo56eh9dciy.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-srx7ar5z2gjyslpzo56eh9dciy]

shape: (31, 1)
┌─────────────────────────────────┐
│ Table                           │
│ ---                             │
│ str                             │
╞═════════════════════════════════╡
│ all_uncurtailedpv               │
│ all_uncurtailedpv_v2            │
│ all_uncurtailedpv_v2_flex_incl… │
│ circuits                        │
│ conformance_antiisland          │
│ …                               │
│ structured_data                 │
│ structured_data_v2              │
│ structured_data_v2_flex_includ… │
│ ts                              │
│ voltwatt_uncurtailedpv          │
└─────────────────────────────────┘

In [6]:
# use this for continued querying of the data
catalog = "iceberg"
with local_trino_engine(catalog = catalog) as engine:
    schemas = pl.read_database(query="SHOW SCHEMAS", connection=engine)

print(schemas)

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-kgfgo7zzzfqjbsjl9i7f66v2ay
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-kgfgo7zzzfqjbsjl9i7f66v2ay.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-kgfgo7zzzfqjbsjl9i7f66v2ay]
shape: (10, 1)
┌─────────────────────────┐
│ Schema                  │
│ ---                     │
│ str                     │
╞═════════════════════════╡
│ bom_nci                 │
│ default                 │
│ elb_logdb               │
│ information_schema      │
│ sapn2022                │
│ solar_analytics         │
│ solar_analytics_iceberg │
│ system                  │
│ test_db                 │
│ type_probe              │
└─────────────────────────┘

In [7]:
# iceberg_sql("SELECT * FROM ts where circuit_id = 239893 and year=2024 and month=10 limit 10")

In [8]:
# passing schema name explicitly, same as defualt here
iceberg_sql("SELECT * FROM sites limit 10", schema = "solar_analytics_iceberg")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-pgdusu5oah7eptxgrjqf8rizqi
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-pgdusu5oah7eptxgrjqf8rizqi.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-pgdusu5oah7eptxgrjqf8rizqi]

shape: (10, 3)
┌────────────┬────────────────┬──────────┐
│ site_id    ┆ ac_capacity_kw ┆ postcode │
│ ---        ┆ ---            ┆ ---      │
│ i64        ┆ f64            ┆ i64      │
╞════════════╪════════════════╪══════════╡
│ 1944472430 ┆ 5.0            ┆ 2502     │
│ 1555410224 ┆ 10.0           ┆ 4814     │
│ 758643151  ┆ 3.6            ┆ 4812     │
│ 1669657679 ┆ 6.0            ┆ 2525     │
│ 1947677239 ┆ 20.0           ┆ 2680     │
│ 565382247  ┆ 10.0           ┆ 4715     │
│ 543357583  ┆ 10.0           ┆ 4740     │
│ 826425816  ┆ 5.0            ┆ 4551     │
│ 1682670886 ┆ 5.0            ┆ 2264     │
│ 1334476516 ┆ 29.9           ┆ 4341     │
└────────────┴────────────────┴──────────┘

In [ ]:
site_metadata = iceberg_sql("SELECT * FROM meta_up23c limit", schema = "solar_analytics_iceberg")
print(site_metadata.shape)

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-rrv2pgqqju7o9kaz3ror9fcg2a
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-rrv2pgqqju7o9kaz3ror9fcg2a.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-rrv2pgqqju7o9kaz3ror9fcg2a]

In [ ]:
# save site metadata from s3 as in sharepoint it was not available, used meta_up23c
# but can also use hive_sql("SELECT * FROM sites limit 5", schema = "solar_analytics")
site_metadata_path = "/Users/z5137801/Documents/CICCADA/LSO_anti_islanding/conformance/datasets/Solar Analytics"
site_metadata.write_csv(site_metadata_path + "/site_metadata.csv")

(60570, 38)

In [15]:
# passing schema name explicitly, same as defualt here
hive_sql("SELECT * FROM sites limit 5", schema = "solar_analytics")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-blrsfyd8hz74divioq9p7kdhia
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-blrsfyd8hz74divioq9p7kdhia.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-blrsfyd8hz74divioq9p7kdhia]

shape: (5, 16)
┌────────────┬───────┬──────────┬───────────┬───┬────────────┬────────────┬────────────┬───────────┐
│ site_id    ┆ state ┆ postcode ┆ longitude ┆ … ┆ manufactur ┆ model      ┆ ac_capacit ┆ installed │
│ ---        ┆ ---   ┆ ---      ┆ ---       ┆   ┆ er         ┆ ---        ┆ y_kw_explo ┆ _after_18 │
│ i64        ┆ str   ┆ f64      ┆ f64       ┆   ┆ ---        ┆ str        ┆ aded       ┆ _dec_2021 │
│            ┆       ┆          ┆           ┆   ┆ str        ┆            ┆ ---        ┆ ---       │
│            ┆       ┆          ┆           ┆   ┆            ┆            ┆ f64        ┆ bool      │
╞════════════╪═══════╪══════════╪═══════════╪═══╪════════════╪════════════╪════════════╪═══════════╡
│ 1944472430 ┆ NSW   ┆ 2502.0   ┆ 150.85    ┆ … ┆ Sungrow    ┆ SG5KTL     ┆ 5.0        ┆ false     │
│ 1555410224 ┆ QLD   ┆ 4814.0   ┆ 146.75    ┆ … ┆ Sungrow    ┆ SG10RS-ADA ┆ 10.0       ┆ true      │
│ 623277618  ┆ QLD   ┆ 4211.0   ┆ 153.3     ┆ … ┆ Fronius    ┆ Primo      ┆ 10.0       ┆ true      │
│            ┆       ┆          ┆           ┆   ┆            ┆ GEN24 10.0 ┆            ┆           │
│ 1245528685 ┆ QLD   ┆ 4078.0   ┆ 152.95    ┆ … ┆ Generic    ┆ 10.0kW     ┆ 10.0       ┆ true      │
│            ┆       ┆          ┆           ┆   ┆ Inverter   ┆            ┆            ┆           │
│ 1651877625 ┆ NSW   ┆ 2350.0   ┆ 151.7     ┆ … ┆ Generic    ┆ 5kW        ┆ 5.0        ┆ false     │
│            ┆       ┆          ┆           ┆   ┆ Inverter   ┆            ┆            ┆           │
└────────────┴───────┴──────────┴───────────┴───┴────────────┴────────────┴────────────┴───────────┘

In [11]:
# passing schema name explicitly, same as defualt here
hive_sql("SELECT * FROM circuits limit 10", schema = "solar_analytics")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-gxuk3zanuxo6v6j93tzsvkotfe
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-gxuk3zanuxo6v6j93tzsvkotfe.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-gxuk3zanuxo6v6j93tzsvkotfe]

shape: (10, 7)
┌────────────┬───────────┬────────────┬──────────────┬──────────────────┬──────────────┬───────┐
│ site_id    ┆ device_id ┆ circuit_id ┆ device_type  ┆ circuit_polarity ┆ circuit_type ┆ is_pv │
│ ---        ┆ ---       ┆ ---        ┆ ---          ┆ ---              ┆ ---          ┆ ---   │
│ i64        ┆ i64       ┆ i64        ┆ str          ┆ i64              ┆ str          ┆ bool  │
╞════════════╪═══════════╪════════════╪══════════════╪══════════════════╪══════════════╪═══════╡
│ 484720983  ┆ 135961    ┆ 84703      ┆ Watt Watcher ┆ 1                ┆ pv_site_net  ┆ true  │
│ 484720983  ┆ 135961    ┆ 84704      ┆ Watt Watcher ┆ 1                ┆ pv_site_net  ┆ true  │
│ 484720983  ┆ 135961    ┆ 84705      ┆ Watt Watcher ┆ 1                ┆ pv_site_net  ┆ true  │
│ 150652475  ┆ 140483    ┆ 658777     ┆ Watt Watcher ┆ 1                ┆ ac_load_net  ┆ false │
│ 150652475  ┆ 140483    ┆ 658778     ┆ Watt Watcher ┆ 1                ┆ ac_load_net  ┆ false │
│ 150652475  ┆ 140483    ┆ 658782     ┆ Watt Watcher ┆ 1                ┆ pv_site_net  ┆ true  │
│ 150652475  ┆ 140483    ┆ 658779     ┆ Watt Watcher ┆ 1                ┆ ac_load_net  ┆ false │
│ 1988982127 ┆ 134898    ┆ 630461     ┆ CATCH Power  ┆ 1                ┆ ac_load_net  ┆ false │
│ 1988982127 ┆ 134898    ┆ 630462     ┆ CATCH Power  ┆ -1               ┆ pv_site_net  ┆ true  │
│ 2137155135 ┆ 135871    ┆ 594217     ┆ Watt Watcher ┆ 1                ┆ ac_load_net  ┆ false │
└────────────┴───────────┴────────────┴──────────────┴──────────────────┴──────────────┴───────┘

In [12]:
iceberg_sql("SELECT * FROM circuits limit 10")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-iyy2e478haijk5u8xrguv6zah4
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-iyy2e478haijk5u8xrguv6zah4.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-iyy2e478haijk5u8xrguv6zah4]

shape: (10, 4)
┌────────────┬────────────┬──────────────────┬───────┐
│ site_id    ┆ circuit_id ┆ circuit_polarity ┆ is_pv │
│ ---        ┆ ---        ┆ ---              ┆ ---   │
│ i64        ┆ i64        ┆ i64              ┆ bool  │
╞════════════╪════════════╪══════════════════╪═══════╡
│ 484720983  ┆ 84703      ┆ 1                ┆ true  │
│ 150652475  ┆ 658777     ┆ 1                ┆ false │
│ 150652475  ┆ 658778     ┆ 1                ┆ false │
│ 150652475  ┆ 658782     ┆ 1                ┆ true  │
│ 150652475  ┆ 658779     ┆ 1                ┆ false │
│ 484720983  ┆ 84704      ┆ 1                ┆ true  │
│ 484720983  ┆ 84705      ┆ 1                ┆ true  │
│ 1988982127 ┆ 630461     ┆ 1                ┆ false │
│ 1988982127 ┆ 630462     ┆ -1               ┆ true  │
│ 2137155135 ┆ 594217     ┆ 1                ┆ false │
└────────────┴────────────┴──────────────────┴───────┘

In [13]:
# this seems like HS created this one
iceberg_sql("SELECT * FROM meta_up23c limit 10")

Starting session with SessionId: z5137801_sa@ad.unsw.edu.au-vy99biav2gfpphauvrhtpghqje
Port 18080 opened for sessionId z5137801_sa@ad.unsw.edu.au-vy99biav2gfpphauvrhtpghqje.
Waiting for connections...

Connection accepted for session [z5137801_sa@ad.unsw.edu.au-vy99biav2gfpphauvrhtpghqje]

shape: (10, 38)
┌────────────┬───────┬──────────┬───────────┬───┬────────┬─────────────┬───────────┬───────────────┐
│ site_id    ┆ state ┆ postcode ┆ longitude ┆ … ┆ n_lat  ┆ distance_km ┆ s_99      ┆ flex_export_d │
│ ---        ┆ ---   ┆ ---      ┆ ---       ┆   ┆ ---    ┆ ---         ┆ ---       ┆ etected       │
│ i64        ┆ str   ┆ i64      ┆ f64       ┆   ┆ f64    ┆ f64         ┆ f64       ┆ ---           │
│            ┆       ┆          ┆           ┆   ┆        ┆             ┆           ┆ bool          │
╞════════════╪═══════╪══════════╪═══════════╪═══╪════════╪═════════════╪═══════════╪═══════════════╡
│ 1233585204 ┆ VIC   ┆ 3140     ┆ 145.35    ┆ … ┆ -37.76 ┆ 1.241018    ┆ 4.614773  ┆ false         │
│ 158521185  ┆ NSW   ┆ 2488     ┆ 153.55    ┆ … ┆ -28.36 ┆ 1.569777    ┆ 7.975964  ┆ false         │
│ 2083958230 ┆ NSW   ┆ 2763     ┆ 150.9     ┆ … ┆ -33.74 ┆ 1.11        ┆ 4.930158  ┆ true          │
│ 248529252  ┆ VIC   ┆ 3140     ┆ 145.35    ┆ … ┆ -37.76 ┆ 1.241018    ┆ 3.9807363 ┆ false         │
│ 248529252  ┆ VIC   ┆ 3140     ┆ 145.35    ┆ … ┆ -37.76 ┆ 1.241018    ┆ 3.9807363 ┆ false         │
│ 248529252  ┆ VIC   ┆ 3140     ┆ 145.35    ┆ … ┆ -37.76 ┆ 1.241018    ┆ 3.9807363 ┆ false         │
│ 804338564  ┆ QLD   ┆ 4670     ┆ 152.45    ┆ … ┆ -24.8  ┆ 1.241018    ┆ 4.819746  ┆ false         │
│ 804338564  ┆ QLD   ┆ 4670     ┆ 152.45    ┆ … ┆ -24.8  ┆ 1.241018    ┆ 4.819746  ┆ false         │
│ 1706869440 ┆ NSW   ┆ 2212     ┆ 151.0     ┆ … ┆ -33.98 ┆ 0.555       ┆ 74.19916  ┆ false         │
│ 1706869440 ┆ NSW   ┆ 2212     ┆ 151.0     ┆ … ┆ -33.98 ┆ 0.555       ┆ 74.19916  ┆ false         │
└────────────┴───────┴──────────┴───────────┴───┴────────┴─────────────┴───────────┴───────────────┘